create table TYPES
(
    ID INT auto_increment,
    ICON VARCHAR not null,
    NAME VARCHAR not null,
    SHORTNAME VARCHAR not null,
    ORDERING INT not null
);

create unique index TYPES_ORDERING_UINDEX
    on TYPES (ORDERING);

create unique index TYPES_ICON_UINDEX
    on TYPES (ICON);

create unique index TYPES_ID_UINDEX
    on TYPES (ID);

create unique index TYPES_NAME_UINDEX
    on TYPES (NAME);

create unique index TYPES_SHORTNAME_UINDEX
    on TYPES (SHORTNAME);


INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-7.png','Pomoc medyczna ambulatoryjna','MED-AMB',1);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-2.png','Jadłodajnia','FOODPLACE',2);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-5.png','Ogrzewalnia','WARMING',3);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-4.png','Łaźnia','SHOWER',4);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-1.png','Jedzenie','FOODSTREET',5);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-3.png','Jadłodzielnia','FOODSHARE',6);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-10.png','Noclegownia','NIGHTSTAY',7);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-6.png','Pomoc medyczna uliczna','MED-STR',8);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-8.png','Odzież','CLOTHING',9);
INSERT INTO PUBLIC.TYPES (ICON, NAME, SHORTNAME, ORDERING) VALUES ('images/icon-9.png','Wsparcie psychologiczne','PSYCHOSUP',10);

alter table PLACES
    add TYPE_SHORTNAME VARCHAR default 'UKNOWN' not null;

comment on column PLACES.TYPE_SHORTNAME is 'foreign key to table types';

update PLACES set TYPE_SHORTNAME='MED-AMB' WHERE STYLE='#icon-1624-A52714';
update PLACES set TYPE_SHORTNAME='FOODPLACE' WHERE STYLE='#icon-1577-FF5252';
update PLACES set TYPE_SHORTNAME='WARMING' WHERE STYLE='#icon-1733-9C27B0';
update PLACES set TYPE_SHORTNAME='SHOWER' WHERE STYLE='#icon-1687-3949AB';
update PLACES set TYPE_SHORTNAME='FOODSTREET' WHERE STYLE='#icon-1577-F9A825';
update PLACES set TYPE_SHORTNAME='FOODSHARE' WHERE STYLE='#icon-1578-558B2F';
update PLACES set TYPE_SHORTNAME='NIGHTSTAY' WHERE STYLE='#icon-1602-0288D1';
update PLACES set TYPE_SHORTNAME='MED-STR' WHERE STYLE='#icon-1624-C2185B';
update PLACES set TYPE_SHORTNAME='CLOTHING' WHERE STYLE='#icon-1683-558B2F';
update PLACES set TYPE_SHORTNAME='PSYCHOSUP' WHERE STYLE='#icon-1592-C2185B';

alter table PLACES drop column STYLE;
